Portfolio: setup and mobile version skeleton
Brenda309/Brenda_portfolio pull request #1
Opened 2022-02-11 12:23 UTC by Brenda309

In this project:

- I build a toolbar section for the mobile version.
- and headline section and for a mobile version.

2022-02-11 20:26 UTC, prolajumokeoni requested changes
Hi @Brenda309 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights 
- Good PR message ✔️ 
- Github was correctly used ✔️ 
- Good readme ✔️ 
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] Kindly add [.stylelintrc.json](https://github.com/microverseinc/linters-config/blob/master/html-css/.stylelintrc.json) and [.hintrc](https://github.com/microverseinc/linters-config/blob/master/html-css/.hintrc) to the root of your project so you can set up linters [environment locally](https://github.com/microverseinc/linters-config/tree/master/html-css-js), also don't forget to add node_modules to .gitignore so you don't add it to git 🤝

![almost-gif](https://user-images.githubusercontent.com/69638013/153665026-dc25d97d-cb37-40db-8376-693da6decd44.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-11 20:26 UTC, prolajumokeoni commented on style.css
> +}
```suggestion
body {
  background-image: url("./images/backgrd.svg");
  background-size: auto;
  background-repeat: no-repeat;
}
```

- [ ] Kindly add the correct path to the image and a background no repeat as suggested above ⬆️ 
- [ ] Kindly add the background image to the right section in your case the "contcontainer" secton

2022-02-11 20:26 UTC, prolajumokeoni commented on index.html
> +            </h2>
- [ ] Kindly use the same fonts colors and  sizes  used in the Figma design

2022-02-11 20:26 UTC, prolajumokeoni commented on README.md
```suggestion

[Live Demo Link](https://livedemo.com)
```

- [ ] Kindly delete live demo link, this can be added when the project is deployed 🤗

2022-02-12 00:02 UTC, nicupop729 requested changes
# Status: Required Changes ♻️

Hi @Brenda309 , 

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![stay-strong-youre-almost-there](https://user-images.githubusercontent.com/65852621/133678845-1b015b27-e9bc-4784-a316-bc699db8237a.jpg)

 ### Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [x] As the previous reviewer only required this as optional, I will do the same. But is highly recommended that you add the `node_modules` folder to the .gitignore file.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-12 00:02 UTC, nicupop729 commented on style.css
> +  display: flex;
Very well implementing the flex display to your container.
The next step is to set the flex-direction in the correct way.

- [ ] Please into consideration to add as a property in this class the following `flex-direction: column;`
If you will do this, your UI will start taking good shape.

2022-02-12 00:09 UTC, nicupop729 commented on index.html
> +            <img src="./images/Union.svg" alt="Menu">
[OPTIONAL]
Because it was not asked by the previous reviewer, I marked it as optional, but I recommend you to change it.

- [ ] The hamburger button in the future will hold some actions, it will display your mobile navigation menu, so I kindly ask you to put it into an `a` or `button` tag

2022-02-12 05:38 UTC, Brenda309 commented on index.html
> +            <img src="./images/Union.svg" alt="Menu">
Hey @nicupop729, Thank you for the  suggestion on the hamburger menu I definitely think if was the button will make the button much better but since the template we were given to use has it there as the image I will keep it that way

2022-02-12 06:55 UTC, AnselemOdims approved these changes
### Hi  @Brenda309 🙋‍♀️, 
Good job in making the required changes 👏 

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Use the tag @AnselemOdims for a quicker reply


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-12 16:00 UTC, merged